Chore/navbar wrapper
TechLadies/united_women_frontend pull request #3
Opened 2019-11-16 13:45 UTC by rcdjasmin

- Wrapped pages in a NavBarWrapper to render navbar
- Switched <Link> to <NavLink>
- Added active state using activeClassName
- Logout button pushed to the bottom

2019-11-17 15:37 UTC, Weiyuan-Lane requested changes

2019-11-17 15:37 UTC, Weiyuan-Lane commented on src/helpers/NavBarWrapper.js
> +function NavBarWrapper(Component) {
@rcdjasmin Looking at the other contents now, I get a better idea now. A suggestion to make this better

```javascript
function NavBarWrapper(Component) {
    return function() {
        return (
            <React.Fragment>
                <NavBar/>
                <main>
                  <Component/>
                </main>
            </React.Fragment>
        )
    }
}
```

We can then remove `main` element repeated on the other page components

2019-11-17 15:37 UTC, Weiyuan-Lane commented on src/components/DonorOverview.js
> +        { editing ? <div className="btn-toolbar mr-2"><SaveButton/><CancelButton/></div> : <EditButton/> }
For this one, the save button and cancel will need some spacing here. let's add a small margin as a spacing between the buttons

2019-11-18 16:18 UTC, rcdjasmin commented on src/components/DonorOverview.js
> +    <button onClick={()=>setEditing(false)} className="btn btn-link">Cancel</button>
@Weiyuan-Lane Changed the Cancel button to btn-link to make the difference between 2 buttons clearer

2019-11-18 16:18 UTC, rcdjasmin commented on src/components/DonorOverview.js
> +    <button onClick={()=>setEditing(false)} className="btn btn-link">Cancel</button>
@Weiyuan-Lane changed the Cancel button to btn-link to make the difference between the 2 buttons clearer

2019-11-20 13:40 UTC, Weiyuan-Lane approved these changes
[![LGTM](https://lgtm.lol/p/493)](https://lgtm.lol/i/493)

2019-11-20 13:40 UTC, merged